name: cvd-12860

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.7    # Python version 3.8
    - jupyterlab    # Jupyter Lab environment
    - numpy
    - matplotlib
    - scipy
    - cartopy
    - pandas
    - hvplot        # Interactive plots with xarray
    - xarray
    - cmocean       # Colormaps for Oceanography
    - cartopy       # Mapping toolbox, projections
    - geoviews      # Flexible visualizations of geospatial data
    - ipywidgets
    - tqdm          # Progress bars